version: '1.0'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_HOST: ${APP_HOST}
        APP_PORT: ${APP_PORT}
    container_name: verveapp
    ports:
      - "${APP_PORT}:${APP_PORT}"
    hostname: "${APP_HOST}"
    environment:
      APP_HOST: ${APP_HOST}
      APP_PORT: ${APP_PORT}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
